-- Paiements V1 + devis + commissions.
-- À exécuter dans l'éditeur SQL Supabase.
-- Ne supprime aucune table, donnée, ni le trigger existant
-- public.trg_protect_payment_row / public.protect_payment_row().

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'ADMIN'
  );
$$;

REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

-- ---------------------------------------------------------------------------
-- Devis
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.booking_quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id bigint NOT NULL REFERENCES public.bookings(id),
  artisan_id uuid NOT NULL REFERENCES public.artisans(id),
  client_id uuid NOT NULL REFERENCES public.profiles(id),
  amount numeric(12,2) NOT NULL CHECK (amount > 0),
  currency text NOT NULL DEFAULT 'XOF',
  status text NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'ACCEPTED', 'REFUSED', 'EXPIRED', 'CANCELLED')),
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS booking_quotes_booking_id_idx
  ON public.booking_quotes (booking_id);

CREATE INDEX IF NOT EXISTS booking_quotes_client_id_idx
  ON public.booking_quotes (client_id);

CREATE INDEX IF NOT EXISTS booking_quotes_artisan_id_idx
  ON public.booking_quotes (artisan_id);

CREATE UNIQUE INDEX IF NOT EXISTS booking_quotes_one_pending_per_booking
  ON public.booking_quotes (booking_id)
  WHERE status = 'PENDING';

CREATE UNIQUE INDEX IF NOT EXISTS booking_quotes_one_accepted_per_booking
  ON public.booking_quotes (booking_id)
  WHERE status = 'ACCEPTED';

ALTER TABLE public.booking_quotes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS booking_quotes_select_participant ON public.booking_quotes;
CREATE POLICY booking_quotes_select_participant
ON public.booking_quotes
FOR SELECT
TO authenticated
USING (
  client_id = auth.uid()
  OR artisan_id = auth.uid()
  OR public.is_admin()
);

-- ---------------------------------------------------------------------------
-- Paiements : colonnes additives uniquement
-- ---------------------------------------------------------------------------

ALTER TABLE public.payments
  ADD COLUMN IF NOT EXISTS quote_id bigint REFERENCES public.booking_quotes(id);

ALTER TABLE public.payments
  ADD COLUMN IF NOT EXISTS payment_method text;

-- Pas d'UPDATE de masse sur payment_method : trg_protect_payment_row
-- rend payment_method immuable.

-- ---------------------------------------------------------------------------
-- Protection existante : conserver le trigger BEFORE UPDATE
-- On remplace uniquement le corps de protect_payment_row() pour
-- ajouter quote_id immuable. On ne DROP PAS trg_protect_payment_row.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.protect_payment_row()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.booking_id IS DISTINCT FROM OLD.booking_id
    OR NEW.client_id IS DISTINCT FROM OLD.client_id
    OR NEW.artisan_id IS DISTINCT FROM OLD.artisan_id
    OR NEW.amount IS DISTINCT FROM OLD.amount
    OR NEW.currency IS DISTINCT FROM OLD.currency
    OR NEW.transaction_reference IS DISTINCT FROM OLD.transaction_reference
    OR NEW.created_at IS DISTINCT FROM OLD.created_at
    OR NEW.payment_method IS DISTINCT FROM OLD.payment_method
    OR NEW.quote_id IS DISTINCT FROM OLD.quote_id
  THEN
    RAISE EXCEPTION 'payment fields immutable';
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF NOT public.is_admin() THEN
      RAISE EXCEPTION 'payment status change not allowed';
    END IF;

    IF NOT (
      (OLD.status = 'PENDING' AND NEW.status IN ('PAID', 'FAILED'))
      OR (OLD.status = 'PAID' AND NEW.status = 'REFUNDED')
    ) THEN
      RAISE EXCEPTION 'transition not allowed';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

-- Le trigger public.trg_protect_payment_row (BEFORE UPDATE) doit rester en place.
-- Ne pas le DROP. S'il pointe déjà vers public.protect_payment_row(),
-- le CREATE OR REPLACE ci-dessus suffit.

-- ---------------------------------------------------------------------------
-- Paramètre de commission (non rétroactif)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.platform_settings (
  key text PRIMARY KEY,
  numeric_value numeric(8,4),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.platform_settings (key, numeric_value)
VALUES ('commission_rate', 0.10)
ON CONFLICT (key) DO NOTHING;

ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS platform_settings_select_admin ON public.platform_settings;
CREATE POLICY platform_settings_select_admin
ON public.platform_settings
FOR SELECT
TO authenticated
USING (public.is_admin());

CREATE TABLE IF NOT EXISTS public.platform_commissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id bigint NOT NULL UNIQUE REFERENCES public.payments(id),
  booking_id bigint NOT NULL REFERENCES public.bookings(id),
  artisan_id uuid NOT NULL REFERENCES public.artisans(id),
  gross_amount numeric(12,2) NOT NULL CHECK (gross_amount > 0),
  commission_rate numeric(8,4) NOT NULL CHECK (commission_rate >= 0 AND commission_rate < 1),
  commission_amount numeric(12,2) NOT NULL CHECK (commission_amount >= 0),
  artisan_amount numeric(12,2) NOT NULL CHECK (artisan_amount >= 0),
  currency text NOT NULL DEFAULT 'XOF',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS platform_commissions_booking_id_idx
  ON public.platform_commissions (booking_id);

ALTER TABLE public.platform_commissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS platform_commissions_select_admin ON public.platform_commissions;
CREATE POLICY platform_commissions_select_admin
ON public.platform_commissions
FOR SELECT
TO authenticated
USING (public.is_admin());

CREATE OR REPLACE FUNCTION public.admin_set_commission_rate(p_rate numeric)
RETURNS numeric
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  IF p_rate IS NULL OR p_rate < 0 OR p_rate >= 1 THEN
    RAISE EXCEPTION 'invalid commission rate';
  END IF;

  INSERT INTO public.platform_settings (key, numeric_value, updated_at)
  VALUES ('commission_rate', p_rate, now())
  ON CONFLICT (key) DO UPDATE
  SET numeric_value = EXCLUDED.numeric_value,
      updated_at = now();

  RETURN p_rate;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_set_commission_rate(numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_set_commission_rate(numeric) TO authenticated;

-- ---------------------------------------------------------------------------
-- Notifications helper
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.notify_account(
  p_user_id uuid,
  p_title text,
  p_message text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_user_id IS NULL THEN
    RETURN;
  END IF;

  INSERT INTO public.notifications (user_id, title, message, is_read)
  VALUES (p_user_id, p_title, p_message, false);
END;
$$;

REVOKE ALL ON FUNCTION public.notify_account(uuid, text, text) FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- RPC artisan : créer un devis
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.artisan_create_booking_quote(
  p_booking_id bigint,
  p_amount numeric,
  p_description text DEFAULT NULL
)
RETURNS public.booking_quotes
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role text;
  v_booking public.bookings;
  v_service public.services;
  v_quote public.booking_quotes;
BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role IS DISTINCT FROM 'ARTISAN' THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'invalid amount';
  END IF;

  SELECT * INTO v_booking
  FROM public.bookings
  WHERE id = p_booking_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'booking not found';
  END IF;

  IF v_booking.artisan_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  IF v_booking.status IS DISTINCT FROM 'ACCEPTED' THEN
    RAISE EXCEPTION 'booking not accepted';
  END IF;

  SELECT * INTO v_service
  FROM public.services
  WHERE id = v_booking.service_id;

  IF NOT FOUND OR v_service.artisan_id IS DISTINCT FROM v_booking.artisan_id THEN
    RAISE EXCEPTION 'invalid service';
  END IF;

  IF v_service.price_type NOT IN ('STARTING_FROM', 'ON_QUOTE') THEN
    RAISE EXCEPTION 'quote not required';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.payments
    WHERE booking_id = v_booking.id
      AND status IN ('PENDING', 'PAID')
  ) THEN
    RAISE EXCEPTION 'active payment exists';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.booking_quotes
    WHERE booking_id = v_booking.id
      AND status = 'ACCEPTED'
  ) THEN
    RAISE EXCEPTION 'accepted quote exists';
  END IF;

  UPDATE public.booking_quotes
  SET status = 'CANCELLED', updated_at = now()
  WHERE booking_id = v_booking.id
    AND status = 'PENDING';

  INSERT INTO public.booking_quotes (
    booking_id, artisan_id, client_id, amount, currency, status, description
  )
  VALUES (
    v_booking.id,
    v_booking.artisan_id,
    v_booking.client_id,
    round(p_amount, 2),
    'XOF',
    'PENDING',
    NULLIF(btrim(COALESCE(p_description, '')), '')
  )
  RETURNING * INTO v_quote;

  PERFORM public.notify_account(
    v_booking.client_id,
    'Devis reçu',
    'L''artisan a proposé un devis pour votre demande.'
  );

  RETURN v_quote;
END;
$$;

REVOKE ALL ON FUNCTION public.artisan_create_booking_quote(bigint, numeric, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.artisan_create_booking_quote(bigint, numeric, text) TO authenticated;

-- ---------------------------------------------------------------------------
-- RPC client : accepter / refuser
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.client_respond_to_booking_quote(
  p_quote_id bigint,
  p_accept boolean
)
RETURNS public.booking_quotes
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role text;
  v_quote public.booking_quotes;
  v_booking public.bookings;
  v_next text;
BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role IS DISTINCT FROM 'CLIENT' THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  SELECT * INTO v_quote
  FROM public.booking_quotes
  WHERE id = p_quote_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'quote not found';
  END IF;

  IF v_quote.client_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  IF v_quote.status IS DISTINCT FROM 'PENDING' THEN
    RAISE EXCEPTION 'quote not pending';
  END IF;

  SELECT * INTO v_booking
  FROM public.bookings
  WHERE id = v_quote.booking_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'booking not found';
  END IF;

  IF v_booking.client_id IS DISTINCT FROM v_quote.client_id
    OR v_booking.artisan_id IS DISTINCT FROM v_quote.artisan_id
  THEN
    RAISE EXCEPTION 'quote booking mismatch';
  END IF;

  IF v_booking.status IS DISTINCT FROM 'ACCEPTED' THEN
    RAISE EXCEPTION 'booking not accepted';
  END IF;

  v_next := CASE WHEN p_accept THEN 'ACCEPTED' ELSE 'REFUSED' END;

  UPDATE public.booking_quotes
  SET status = v_next, updated_at = now()
  WHERE id = v_quote.id
    AND status = 'PENDING'
  RETURNING * INTO v_quote;

  IF p_accept THEN
    PERFORM public.notify_account(
      v_quote.client_id,
      'Devis accepté',
      'Vous avez accepté le devis. Vous pouvez maintenant préparer le paiement.'
    );
    PERFORM public.notify_account(
      v_quote.artisan_id,
      'Devis accepté',
      'Le client a accepté votre devis.'
    );
  ELSE
    PERFORM public.notify_account(
      v_quote.client_id,
      'Devis refusé',
      'Vous avez refusé le devis proposé.'
    );
    PERFORM public.notify_account(
      v_quote.artisan_id,
      'Devis refusé',
      'Le client a refusé votre devis.'
    );
  END IF;

  RETURN v_quote;
END;
$$;

REVOKE ALL ON FUNCTION public.client_respond_to_booking_quote(bigint, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.client_respond_to_booking_quote(bigint, boolean) TO authenticated;

-- ---------------------------------------------------------------------------
-- Paiement FIXED : transaction_reference posé à l'INSERT, jamais en UPDATE
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.create_payment_for_booking(p_booking_id bigint)
RETURNS public.payments
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role text;
  v_booking public.bookings;
  v_service public.services;
  v_payment public.payments;
  v_amount numeric(12,2);
  v_reference text;
BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role IS DISTINCT FROM 'CLIENT' THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  SELECT * INTO v_booking
  FROM public.bookings
  WHERE id = p_booking_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'booking not found';
  END IF;

  IF v_booking.client_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  IF v_booking.status IS DISTINCT FROM 'ACCEPTED' THEN
    RAISE EXCEPTION 'booking not accepted';
  END IF;

  SELECT * INTO v_service
  FROM public.services
  WHERE id = v_booking.service_id;

  IF NOT FOUND OR v_service.artisan_id IS DISTINCT FROM v_booking.artisan_id THEN
    RAISE EXCEPTION 'invalid service';
  END IF;

  IF v_service.price_type IS DISTINCT FROM 'FIXED' THEN
    RAISE EXCEPTION 'quote required';
  END IF;

  IF v_service.price IS NULL OR v_service.price <= 0 THEN
    RAISE EXCEPTION 'invalid price';
  END IF;

  v_amount := round(v_service.price, 2);

  IF EXISTS (
    SELECT 1 FROM public.payments
    WHERE booking_id = v_booking.id
      AND status IN ('PENDING', 'PAID')
  ) THEN
    RAISE EXCEPTION 'active payment exists';
  END IF;

  v_reference := 'AA-' || v_booking.id::text || '-' || replace(gen_random_uuid()::text, '-', '');

  INSERT INTO public.payments (
    booking_id,
    client_id,
    artisan_id,
    amount,
    currency,
    status,
    payment_method,
    transaction_reference
  )
  VALUES (
    v_booking.id,
    v_booking.client_id,
    v_booking.artisan_id,
    v_amount,
    'XOF',
    'PENDING',
    'MANUAL',
    v_reference
  )
  RETURNING * INTO v_payment;

  PERFORM public.notify_account(
    v_booking.client_id,
    'Paiement créé',
    'Un paiement est en cours de préparation pour votre demande.'
  );

  RETURN v_payment;
END;
$$;

REVOKE ALL ON FUNCTION public.create_payment_for_booking(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_payment_for_booking(bigint) TO authenticated;

-- ---------------------------------------------------------------------------
-- Paiement après devis accepté
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.create_payment_for_accepted_quote(p_booking_id bigint)
RETURNS public.payments
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role text;
  v_booking public.bookings;
  v_service public.services;
  v_quote public.booking_quotes;
  v_payment public.payments;
  v_reference text;
BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role IS DISTINCT FROM 'CLIENT' THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  SELECT * INTO v_booking
  FROM public.bookings
  WHERE id = p_booking_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'booking not found';
  END IF;

  IF v_booking.client_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  IF v_booking.status IS DISTINCT FROM 'ACCEPTED' THEN
    RAISE EXCEPTION 'booking not accepted';
  END IF;

  SELECT * INTO v_service
  FROM public.services
  WHERE id = v_booking.service_id;

  IF NOT FOUND OR v_service.artisan_id IS DISTINCT FROM v_booking.artisan_id THEN
    RAISE EXCEPTION 'invalid service';
  END IF;

  IF v_service.price_type NOT IN ('STARTING_FROM', 'ON_QUOTE') THEN
    RAISE EXCEPTION 'quote not required';
  END IF;

  SELECT * INTO v_quote
  FROM public.booking_quotes
  WHERE booking_id = v_booking.id
    AND status = 'ACCEPTED'
    AND client_id = v_booking.client_id
    AND artisan_id = v_booking.artisan_id
  ORDER BY created_at DESC
  LIMIT 1
  FOR UPDATE;

  IF NOT FOUND OR v_quote.amount IS NULL OR v_quote.amount <= 0 THEN
    RAISE EXCEPTION 'accepted quote required';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.payments
    WHERE booking_id = v_booking.id
      AND status IN ('PENDING', 'PAID')
  ) THEN
    RAISE EXCEPTION 'active payment exists';
  END IF;

  v_reference := 'AA-' || v_booking.id::text || '-' || replace(gen_random_uuid()::text, '-', '');

  INSERT INTO public.payments (
    booking_id,
    client_id,
    artisan_id,
    amount,
    currency,
    status,
    payment_method,
    transaction_reference,
    quote_id
  )
  VALUES (
    v_booking.id,
    v_booking.client_id,
    v_booking.artisan_id,
    round(v_quote.amount, 2),
    COALESCE(NULLIF(v_quote.currency, ''), 'XOF'),
    'PENDING',
    'MANUAL',
    v_reference,
    v_quote.id
  )
  RETURNING * INTO v_payment;

  PERFORM public.notify_account(
    v_booking.client_id,
    'Paiement créé',
    'Un paiement est en cours de préparation pour le devis accepté.'
  );

  RETURN v_payment;
END;
$$;

REVOKE ALL ON FUNCTION public.create_payment_for_accepted_quote(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_payment_for_accepted_quote(bigint) TO authenticated;

-- ---------------------------------------------------------------------------
-- Transitions de statut : ADMIN uniquement (RPC). Pas d'UPDATE libre frontend.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.admin_set_payment_status(
  p_payment_id bigint,
  p_new_status text
)
RETURNS public.payments
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_payment public.payments;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  IF p_new_status NOT IN ('PAID', 'FAILED', 'REFUNDED') THEN
    RAISE EXCEPTION 'invalid status';
  END IF;

  SELECT * INTO v_payment
  FROM public.payments
  WHERE id = p_payment_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'payment not found';
  END IF;

  IF NOT (
    (v_payment.status = 'PENDING' AND p_new_status IN ('PAID', 'FAILED'))
    OR (v_payment.status = 'PAID' AND p_new_status = 'REFUNDED')
  ) THEN
    RAISE EXCEPTION 'transition not allowed';
  END IF;

  UPDATE public.payments
  SET status = p_new_status
  WHERE id = p_payment_id
    AND status = v_payment.status
  RETURNING * INTO v_payment;

  RETURN v_payment;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_set_payment_status(bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_set_payment_status(bigint, text) TO authenticated;

-- ---------------------------------------------------------------------------
-- AFTER UPDATE : notifications + commissions uniquement.
-- Ne protège PAS les champs ni les transitions (déjà gérés par
-- trg_protect_payment_row / protect_payment_row).
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.payments_notify_and_commission()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_rate numeric(8,4);
  v_commission numeric(12,2);
  v_artisan numeric(12,2);
BEGIN
  IF NEW.status IS NOT DISTINCT FROM OLD.status THEN
    RETURN NEW;
  END IF;

  IF OLD.status = 'PENDING' AND NEW.status = 'PAID' THEN
    PERFORM public.notify_account(
      NEW.client_id,
      'Paiement confirmé',
      'Votre paiement a été confirmé.'
    );
    PERFORM public.notify_account(
      NEW.artisan_id,
      'Paiement confirmé',
      'Un paiement a été confirmé pour une de vos interventions.'
    );

    SELECT numeric_value INTO v_rate
    FROM public.platform_settings
    WHERE key = 'commission_rate';

    IF v_rate IS NOT NULL AND v_rate >= 0 AND v_rate < 1 THEN
      v_commission := round(NEW.amount * v_rate, 2);
      v_artisan := round(NEW.amount - v_commission, 2);

      INSERT INTO public.platform_commissions (
        payment_id, booking_id, artisan_id, gross_amount,
        commission_rate, commission_amount, artisan_amount, currency
      )
      VALUES (
        NEW.id, NEW.booking_id, NEW.artisan_id, NEW.amount,
        v_rate, v_commission, v_artisan, COALESCE(NEW.currency, 'XOF')
      )
      ON CONFLICT (payment_id) DO NOTHING;
    END IF;
  ELSIF OLD.status = 'PENDING' AND NEW.status = 'FAILED' THEN
    PERFORM public.notify_account(
      NEW.client_id,
      'Paiement échoué',
      'Le paiement n''a pas pu être confirmé.'
    );
  ELSIF OLD.status = 'PAID' AND NEW.status = 'REFUNDED' THEN
    PERFORM public.notify_account(
      NEW.client_id,
      'Remboursement',
      'Un remboursement a été enregistré.'
    );
    PERFORM public.notify_account(
      NEW.artisan_id,
      'Remboursement',
      'Un remboursement a été enregistré pour une intervention.'
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_payments_quotes_guard ON public.payments;
DROP TRIGGER IF EXISTS trg_payments_notify_and_commission ON public.payments;

CREATE TRIGGER trg_payments_notify_and_commission
AFTER UPDATE ON public.payments
FOR EACH ROW
EXECUTE FUNCTION public.payments_notify_and_commission();

GRANT SELECT ON public.booking_quotes TO authenticated;
GRANT SELECT ON public.platform_commissions TO authenticated;
GRANT SELECT ON public.platform_settings TO authenticated;
